spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  mail:
    host: smtp.qq.com
    port: 587
    username: 3521167562@qq.com
    password: rnybqkoiyaxldagc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      port: 6379
      host: 127.0.0.1




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印SQL语句
  mapper-locations: classpath*:mapper/*.xml # 指定映射文件位置
  type-aliases-package: com.mt.dao.entity # 实体类包路径